name: Build Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: |
        npm install -g @capacitor/cli
        npm install
        
    - name: Initialize Capacitor
      run: |
        npx cap init GitHubMgr com.example.githubmgr --web-dir=dist
        npm install @capacitor/android
        npx cap add android
        
    - name: Build and package
      run: |
        # 复制你的HTML文件到dist目录
        mkdir -p dist
        cp index.html dist/
        cp -R assets/ dist/ || true
        
        # 构建并打包APK
        npx cap sync android
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-mgr-app
        path: android/app/build/outputs/apk/debug/app-debug.apk